### ISSUE TITLE
Documentation/wiki updates

### ISSUE THREAD

**Issue by rpedrica** [bmcgonag/docker_installs#10]
Hi Brian

3 items to improve on your script:

1. password info in docker-compose files

Your compose files have some generic password info eg. "password" for influxdb in the speedtest_grafana container stack. Can I suggest you note this in your README so that noobies are not caught off guard with "scurge of the defaults" ...

2. your speedtest_grafana stack specifically uses a significant of data which I got caught out with on my test Linode instance (140GB in a 12 hr period) - maybe note this in the README for those not expecting it; you can also mention to extend the SPEEDTEST_INTERVAL env variable in the yml file

3. the speedtest_grafana stack has no dashboard setup by default and I'm guessing you have to add the influxdb source or import a json file - I've done the import by getting the speedtest.json file form the original project - might be useful to add some information about this otherwise some are going to be in the dark

Regards, Robby

**Comment by bmcgonag** [comment]
Thanks, yeah, something weird happened with that speedtest one.  I haven't changed anything and it used to have the dashboard, but now it doesn't, so not sure why.  

I'll probably just remove that as an option.  It was really just for my testing anyway.

**Comment by rpedrica** [comment]
Thanks, and thanks for the script - makes setting a docker server quick and easy!
