### ISSUE TITLE
Update Portainer

### ISSUE THREAD

**Issue by patryck507** [bmcgonag/docker_installs#15]
Hello i have Docker-CE, Docker-Compose, NGinX Proxy Manager, and Portainer-CE. and i have no clue how to update Portainer now, would be great if some could help me out

**Comment by bmcgonag** [comment]
I generally just stop portainer, then remove it, do a pull for the new
version, and re-run the portainer run command.

So, run the following:

docker stop portainer

docker rm portainer

docker pull portainer/portainer-ce

docker run -d -p 9000:9000 --name portainer --restart=always -v
/var/run/docker.sock:/var/run/docker.sock -v p
ortainer_data:/data portainer/portainer-ce:latest

That should get you up and running on the newest version of Portainer
Community Edition.

If you need the portainer-agent, then just replace "portainer-ce" with
"portainer-agent" and change the port mapping section to 9001:9001 .

Brian McGonagill

**Comment by patryck507** [comment]
thanks for the fast response. there are no risks? username and password stay the same?

edit: worked fine without any problems, thank you very much!

**Comment by bmcgonag** [comment]
Shouldn’t be. 

Brian McGonagill
