### ISSUE TITLE
insstall_docker_nproxyman.sh fix

### ISSUE THREAD

**Issue by JayGreentree-Codes** [bmcgonag/docker_installs#2]
insstall_docker_nproxyman.sh works well on my ubuntu test machine but needs **exit 1** set to prevent it from looping back to the start after completion.

**Comment by bmcgonag** [comment]
Added "exit 1" at the end of the function. Let me know if that does it.

**Comment by bmcgonag** [comment]
Tested on ubuntu 20.04 server on Digital Ocean, and it exited after script completed selected tasks.  This isn't specific to any distro, so I think it should be good.
