### ISSUE TITLE
getting error messages

### ISSUE THREAD

**Issue by x81kilo** [bmcgonag/docker_installs#7]
Not sure if this is an issue, I am really new to using ubuntu and git also :-) but thank you for the sh script.  

1)  Full Portainer-CE (Web GUI for Docker, Swarm, and Kubernetes)
2)  Portainer Agent - Remote Agent to Connect from Portainer-CE
3)  Nevermind -- I don't need Portainer after all.
Please choose either Portainer-CE or just Portainer Agent: 1
#######################################################
#######################################################

    1. Installing System Updates... this may take a while...be patient.
    2. Installing Docker-CE (Community Edition)...
./dockerinstall.sh: line 115: curl: command not found
- docker-ce version is now:
./dockerinstall.sh: line 118: docker: command not found

  - Attempting to add the currently logged in user to the docker group...
  - You'll need to log out and back in to finalize the addition of your user to the docker group.

**Comment by x81kilo** [comment]
##########################################
###     Install NGinX Proxy Manager    ###
##########################################
    1. Pulling a default NGinX Proxy Manager docker-compose.yml file.
    2. Running the docker-compose.yml to install and start NGinX Proxy Manager
Additional error on nginx proxy section

**ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        


    Navigate to your server hostname / IP address on port 81 to setup
    NGinX Proxy Manager admin account.**

**Comment by bmcgonag** [comment]
Sorry for the delay in response. Can you look for a .log file in the directory where you ran the script from, and pleasae attach it to a reply for me to look at.  Also, I've moved the script home to GitLab.  It's at https://gitlab.com/bmcgonag/docker_installs

You can download the most recent script from there with 
`wget https://gitlab.com/bmcgonag/docker_installs/-/raw/main/install_docker_nproxyman.sh`

And try that one.  I'll update this repo with those changes shortly.
