### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by titostl1** [bmcgonag/docker_installs#8]
I am running into a syntax error when run the script. Any help will be appreciated. 

./docker-install.sh: line 85: syntax error near unexpected token `"Full Portainer-CE (Web GUI for Docker, Swarm, and Kubernetes)"'
./docker-install.sh: line 85: `           "Full Portainer-CE (Web GUI for Docker, Swarm, and Kubernetes)" \'

**Comment by bmcgonag** [comment]
Hmmmm.  Not sure why. I've got an updated script over at Gitlab. I'm migrating over to Gitlab for most of my projects, but I'll be updating this site occasionally. I will update this script shortly with those changes.  You can get them directly from GitLab with 

`wget https://gitlab.com/bmcgonag/docker_installs/-/raw/main/install_docker_nproxyman.sh`

if you'd like to try the more up to date script.
